- index.js
Can use mirror like http://npm.taobao.org/mirrors/electron/
> Add ELECTRON_MIRROR

- cli.js
- index.js
- package.json
- readme.md
- test.js
- Added CLI use support
- Added mirror opt as well as ELECTRON_MIRROR
> Added CLI use support

- index.js
- package.json
- test_symbols.js
Added options to download debug symbols package.
> Added flag to download debug symbols

- cli.js
- index.js
I'm not a "javascript guy", but submitting a change to allow ignoring strict SSL checking (because corporate proxies woo).
> Adding option to disable strict SSL verification

- index.js
Added support for electron mirror in npm config
> Added npm config support

- index.js
> take the npm strict-ssl setting into account

- index.js
- package.json
Update to the latest major versions and update the use of their APIs accordingly.
> Update nugget & path-exists dependencies

- .npmignore
- .travis.yml
- appveyor.yml
- readme.md
- test_symbols.js
Adds AppVeyor CI to verify the tests pass on Windows.
> Add AppVeyor config

- readme.md
Show downloads in npm badge in README.
> Add download count to npm badge

- lib/index.js
- test/test_dsym.js
Adds support for downloading the `dSYM` assets published with each release.
> Add support for downloading macOS dSYM zips

- lib/index.js
- test/test_chromedriver.js
Support new version in asset name starting in 1.7.0
Refs https://github.com/electron/electron/pull/8682
> Support new version in Chromedriver asset name

- lib/index.js
- test/test_autodownload.js
Fixes #57
This allows you to disable downloading missing files
> Add autoDownload option

- lib/index.js
- readme.md
- test/test.js
Fixes #51
Not convinced on adding this but I can see it being useful for at least local Electron dev so 🤔
> Add option to disable checksum checking

- package.json
- src/index.ts
- tsconfig.json
- typings/ambient.d.ts
- yarn.lock
`sumchecker` v3 comes with its own typings file.
> chore: upgrade sumchecker to ^3.0.0

- src/GotDownloader.ts
This is needed for a lot of functionality that people expect from Electron Packager.
> feat: pass in downloader options to got

- .circleci/config.yml
- .gitignore
- README.md
- package.json
- src/GotDownloader.ts
- src/index.ts
- src/types.ts
- yarn.lock
Attempts to fix #92. It'd be nice if it could be auto-uploaded as GitHub pages, but :man_shrugging:
> Add docs & typedoc support

- package.json
- src/Cache.ts
- src/index.ts
- yarn.lock
> feat: add debug support

- script/publish-docs.js
There's a reasonable chance it'll publish this time :grin:
> chore: add default GitHub repository value in doc publish script

- package.json
- yarn.lock
The bug described in https://github.com/electron/get/pull/95 has been fixed.
> chore: upgrade fs-extra to ^8.1.0 & @types/fs-extra to ^8.0.0

- src/artifact-utils.ts
- test/artifact-utils.spec.ts
Fixes https://github.com/electron/get/issues/106
> fix: actually use the artifactSuffix when generating the filename

- src/index.ts
- src/types.ts
- test/index.spec.ts
> feat: make platform and arch optional in downloadArtifact

- yarn.lock
Fixes the fs-extra windows issues we see on CI
> build: ensure only one instance of graceful-fs

- README.md
- test/artifact-utils.spec.ts
Addresses #116.
Also increases practical test coverage.
> Document and test mirror options

- src/index.ts
- test/index.spec.ts
Alternate proposal to #137 
Closes #137
~~Blocked by #141~~
CC: @dsanders11
>  fix: default falsy platform/arch to host values 

- README.md
- src/artifact-utils.ts
- test/artifact-utils.spec.ts
Alternate proposal for #134.
Closes #123 
Closes #134
> feat: allow bare version placeholder to be replaced in customDir

- package.json
- src/Cache.ts
- src/GotDownloader.ts
- src/artifact-utils.ts
- src/downloader-resolver.ts
- src/index.ts
- src/proxy.ts
- src/types.ts
- src/utils.ts
- test/FixtureDownloader.ts
- test/GotDownloader.network.spec.ts
- test/artifact-utils.spec.ts
- test/index.spec.ts
- test/utils.spec.ts
- yarn.lock
Follow-up to https://github.com/electron/get/pull/182#discussion_r561418583. It's mostly moving code around, adding/clarifying type annotations, and ignoring a bunch of `any`s :grimacing: 
Requires #183.
> chore: add eslint

- test/checksums.spec.ts
- test/utils.spec.ts
See: https://nodejs.org/api/process.html#processconfig
> test: improve `process.config` code

- .github/workflows/docs.yml
Use a GitHub app to update the docs so we can better tighten down branch restrictions.
> ci: use GitHub app for commits

- .github/workflows/docs.yml
`malept/github-action-gh-pages` stages the changes to commit, and `dsanders11/github-app-commit-action` commits them.
> ci: make signed commits when publishing docs
