index.js

The directory structure of http://npm.taobao.org/mirrors/electron/ has been changed.
It's clear now.

Change the url base of ECTRON_MIRROR

---

index.js
package.json
test_404.js

Adds a custom 404 message that front-loads the version, platform, and arch information.
This is an attempt to better showcase there is no Electron version for certain platform/arch combinations such as 32-bit Mac.
Refs https://github.com/atom/electron/issues/4655
/cc @jlord :pear:

Add custom 404 message

---

index.js
readme.md

Internally we would like to use our own mirror which does not conform to the `ELECTRON_MIRROR`/`VERSION`/`NAME`. Would you accept a PR like this?

Allow customization of URL directory and filename

---

index.js

The repository has moved from the Atom org to the Electron org, https://github.com/electron/electron

Use repo under electron org

---

cli.js
index.js
package.json
test.js
test_404.js
test_symbols.js

Refactor the entirety of `index.js` to be an ES6 class. This was done mostly because it was going to take a refactor to add support for #19, anyway. In my opinion, this at least makes it more obvious as to how the module works.
This makes Node >= 4 a hard requirement, but Travis is only testing Node >=4 right now anyway.
Also, replaces `standard` with `eslint` plus the standard plugin and `'use strict'` check.

Convert to ES6

---

index.js
readme.md

No idea why latest npm set .npmrc variables with lower-case prefix `npm_config_` 
```
$ node -v
v6.3.1
$ npm -v
3.10.3
$ cat .npmrc
registry=https://registry.npm.taobao.org
ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/
$ npm run env | grep MIRROR
npm_config_ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/
```
And node-sass had changed it to [use lower-case prefix](https://github.com/sass/node-sass/blob/586a6760d2e962224b59a474a35cb781f9c24382/lib/extensions.js#L222).
So add as an fallback? Also fix #17;

allow npmrc variable for ELECTRON_MIRROR

---

index.js
package.json
readme.md
test.js
test_404.js
test_with_checksum.js

When an Electron release has a `SHASUMS256.txt` available, it will parse that file and verify that the checksum for the given file matches what is generated by the `sumchecker` module using the contents of the file. If the file does not match, it is deleted from the Electron cache and an error is thrown.
This PR also replaces `mkdirp` and `mv` with `fs-extra`, since I had to use `fs.unlink` anyway.
CC: @kevinsawicki @zeke 
Fixes #19.

Add SHASUMS256.txt checking

---

index.js
test/test.js
test/test_404.js
test/test_symbols.js
test/test_with_checksum.js

Allow `quiet` to be a configurable option that gets passed through to `nugget`.
Still defaults to `false` but can be overridden, such as by the specs, for less-noisy CI output.

Add quiet option to pass through to nugget

---

lib/index.js

Until the root cause of https://github.com/electron-userland/electron-prebuilt/issues/193 is tracked down just disable the progress bar when there `stdout.rows` is `0` meaning the progress bar isn't showable.
This seems to be the case on Mac Travis CI workers.
Closes #34

Enable quiet mode when no room to show progress bar

---

lib/index.js
package.json
test/test_bad_config.js

Looks like the `rc` library will throw errors for invalid JSON files but not include the file path being parsed.
This can make debugging hard since it looks in several location and it prevents Electron from being installed.
This pull request catches these errors and logs them but allows downloading to complete since the `npmrc` settings are often unused/optional and aren't required for installation.
Closes https://github.com/electron/electron/issues/8188

Catch npm rc parsing errors

---

lib/index.js
readme.md
test/test_chromedriver.js
test/test_ffmpeg.js
test/test_mksnapshot.js

Currently only Electron and the symbols can be downloaded.
This pull request adds support for the Chromedriver, mksnapshot, and ffmpeg assets that are included in Electron releases.
This will be used by https://github.com/electron/chromedriver and https://github.com/electron/mksnapshot so they can consistently support proxies, shasum validation, logging, etc.

Support downloading other Electron assets

---

lib/index.js
package.json
readme.md
test/helpers.js
test/test.js

Add a `force` boolean option that when set will re-download the asset and the `SHASUM` file to the cache area.
/cc @pfrazee would this option work for your use case?
Closes #38

Add force option to redownload

---

.gitignore
.npmignore
.travis.yml
appveyor.yml
lib/index.js
package.json
readme.md
test/test_bad_config.js

Hopefully this goes a bit better than when I removed both of these things from sumchecker.
Per the policy, this will require a major version bump.
Closes #40.

Remove Node 0.12 support and Babel

---

lib/index.js
package.json
readme.md
test/test.js

The cache is saved to a standard cache directory using the "env-paths"
module, rather than saving in the home directory.
The old cache directory will automatically be migrated to the new
location.
BREAKING CHANGE: Cache is no longer stored in `~/.electron`.

Save cache to standard directory

---

lib/index.js
test/test_fallback.js

See @develar's concerns at the original issue #24 and at the [atomic rename PR](https://github.com/electron-userland/electron-download/pull/47#issuecomment-292803245).
I have included a test that fails against master and is passing by moving the fallback logic to directory level.

Fix fallback location

---

lib/cli.js
lib/index.js
package.json
readme.md

Because on CI server system-specific location (multi CI like Travis allows) complicates cache configuration.

Electron cache env

---

lib/index.js
readme.md

There were some inconsistencies here; you could specify the mirror base URL in npm config and .npmrc, but not middleUrl or urlSuffix (filename). This change rectifies that and allows you to specify baseUrl, middleUrl and urlSuffix in the consuming project's [package.json `config` block](https://docs.npmjs.com/files/package.json#config)

get baseUrl, middleUrl and filename from package

---

lib/arch.js
lib/index.js
package.json
test/test_arch.js

Determine which specific ARM version a given host arch is running, so the appropriate Electron binary is selected. This is particularly important as of Electron 3, since `-arm` builds are no longer being created.
This basically moves `hostArch` from Electron Packager into this package.
Fixes https://github.com/electron/electron/issues/13745.

Determine arch on ARM hosts better

---

README.md
src/index.ts
src/utils.ts
test/utils.spec.ts

* Fix `uname` test on Linux
* Sync API examples in the README with the actual API
* Rename/refactor the host arch API and re-export getHostArch so it can be used in places such as Electron Packager.

Update arch API/docs

---

src/artifact-utils.ts
src/index.ts
src/utils.ts

Those using typescript will get compile errors, we should still have some handy warnings for those not using typescript so they get more descriptive errors than "can not read property startsWith of undefined".

fix: add user-friendly validation when an invalid input object is provided

---

package.json
yarn.lock

Fixes [an EPERM bug](https://github.com/jprichardson/node-fs-extra/issues/684) on Windows.

fix: downgrade fs-extra to ^7.0.1

---

package.json
tsconfig.json
typings/ambient.d.ts
yarn.lock

2.2.0 contains its own TypeScript definition, so there does not need to be any ambient typings.

chore: raise env-paths requirement to ^2.2.0

---

src/index.ts
src/utils.ts
test/utils.spec.ts

Linux/ia32 support was deprecated as of 4.0.0, see blog post: https://electronjs.org/blog/linux-32bit-support

feat: emit warning if downloading a deprecated linux/ia32 binary

---

.circleci/config.yml
.github/publish-docs.workflow
package.json
script/publish-docs.js
yarn.lock

Uses the `gh-pages` module plus the fancy new GitHub Actions to publish the generated API docs to GitHub pages on every commit.

chore: publish docs to GitHub Pages

---

src/index.ts

This PR will
- export all types so interfaces like `ElectronDownloadRequestOptions` can be imported.
cc @MarshallOfSound @malept

fix: Export all types

---

package.json
script/publish-docs.js

I figured out how to locally test the silly thing and "it works on my machine":tm:
It's mostly the change to `publish:docs`.

chore: fix up publishing docs to GitHub repo

---

src/index.ts

Fixes https://github.com/electron/get/issues/108

fix: ensure the SHASUM download call provides mirrorOptions

---

package.json
src/Cache.ts
src/artifact-utils.ts
src/index.ts
test/Cache.spec.ts
test/artifact-utils.spec.ts
test/index.spec.ts
yarn.lock

The cache right now ignores multiple mirrors used simultaneously on the same machine.
I can lead to some non-obvious build issues.
This changes the cache files structure to the following:
```
/
httpsgithub.comelectronelectronreleasesdownloadv5.0.9chromedriver-v5.0.9-darwin-x64.zip /
chromedriver-v5.0.9-darwin-x64.zip
httpsmyawesomemirror.comelectronv5.0.9chromedriver-v5.0.9-darwin-x64.zip /
chromedriver-v5.0.9-darwin-x64.zip  // from a mirror
httpsgithub.comelectronelectronreleasesdownloadv5.0.9electron.d.ts /
electron.d.ts
httpsgithub.comelectronelectronreleasesdownloadv6.0.2electron.d.ts /
electron.d.ts  // a different version
```

feat: make the cache to respect an artifact url

---

README.md
package.json
src/index.ts
src/proxy.ts
yarn.lock

Folks are having trouble with using this module behind corporate proxies (example: https://github.com/electron/electron-packager/issues/1019). This pull request adds a method (code borrowed from yeoman) that will add environment variable support. See the new section of the README for details.
Downstream packages I expect to provide PRs for, if this is merged:
* `electron`
* `electron-packager`
* `@electron-forge/cli`
* `fiddle`, I think?
https://electronjs.org/docs/tutorial/installation#proxies will have to be modified slightly once `electron/electron` is updated (not that it's accurate right now anyway...)

feat: add initializeProxy helper for downstream packages

---

src/index.ts
src/types.ts
src/utils.ts

Sometimes `os.tmpdir()` is not the best place to store temporary files. Let' give user more control over it.

feat: add optional "tempDirectory" download request option

---

src/utils.ts
test/utils.spec.ts

In the case where `process.config.variable.arm_version` is undefined `arm` ends up being used as the arch which is not a valid arch for Electron, so this PR changes that case to return `armv7l` so that a valid arch is returned.
Resolves https://github.com/electron/electron/issues/21070

fix: use armv7l if process.config.variable.arm_version is undefined

---

README.md

When I updated #118 to use an environment variable, I forgot to add the supporting docs for it. This PR rectifies that.

docs: update proxy docs with environment variable

---

package.json
src/index.ts
yarn.lock

This fixes the TypeScript definitions so we don't have to use `require()` for `sumchecker`.

chore(deps): upgrade sumchecker to 3.0.1

---

tsconfig.json

This generates much less unnecessary code for the Node versions we're targeting.
According to https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping, ES2017 corresponds with Node 8.

build: have tsc emit Node 8-compatible JS

---

src/GotDownloader.ts
test/GotDownloader.network.spec.ts

Addresses #122.
Fixes #125.
Depends on #138.

fix(GotDownloader): destroy the writeStream if possible when the download errors

---

src/GotDownloader.ts
test/GotDownloader.network.spec.ts

This should make the issues filed about 404 errors easier to figure out.
Depends on #145.

fix(GotDownloader): add URL to 404 error message

---

.github/workflows/docs.yml

Attempt number 3.
Uses the same GitHub Actions workflow as Electron Packager.

build: publish docs to GitHub Pages

---

README.md
src/index.ts
test/index.spec.ts

This PR adds support for an environment variable, `ELECTRON_CUSTOM_VERSION`, that allows overriding the version downloaded.  I also added some brief documentation on the mirror environment variables that resolves #126.
One use case for this feature is to allow overriding the version of Electron specified in package.json so that CI on Electron apps can test against newer Electron versions.

feat: add environment variable to override version downloaded

---

README.md
package.json
src/artifact-utils.ts
src/types.ts
test/artifact-utils.spec.ts
yarn.lock

In some cases the url passed with a mirror will be fully-formed and not have `path/name` at the end, meaning that the current logic will tack it on and cause failures. This fixes that by optionally allowing only the base url to be passed to got for download.
cc @MarshallOfSound

feat: allow optionally only passing a base url to downloadArtifact

---

README.md
src/artifact-utils.ts
src/index.ts
src/types.ts
test/artifact-utils.spec.ts

Follow-up to https://github.com/electron/get/pull/156.
Refs https://github.com/electron/get/pull/156#discussion_r420974703.
Allow custom URL resolution with `resolveAssetURL`.
cc @MarshallOfSound

feat: allow custom URL resolution with resolveAssetURL

---

src/Cache.ts
test/Cache.spec.ts

Solves an issue with cache misses caused by urls that differ in their query params by stripping hash and query params from cache key.
cc @MarshallOfSound

refactor: strip hash and query params from cache key

---

README.md
src/artifact-utils.ts
src/types.ts
test/artifact-utils.spec.ts

Fixes a variable inconsistency in `mirrorOptions` - all variables were camelCase except `nightly_mirror`.
cc @malept

fix: deprecate mirrorOptions.nightly_mirror in favor of mirrorOptions.nightlyMirror

---

yarn.lock

`master` has its `yarn.lock` out of sync with `package.json`. I ran `yarn` (without any changes in the repo) and got these updates.

chore: sync yarn.lock with package.json

---

package.json
src/Cache.ts
test/Cache.spec.ts
yarn.lock

It's extremely difficult to upgrade `sanitize-filename` from 1.6.2 to 1.6.3, as they merged their TypeScript typings into the package. As a result, the recommended import statement to use it does not seem to work with both CJS and ESM configurations.
The options used with `filenamify` should be compatible with the default options of `sanitize-filename`.

refactor(Cache): replace sanitize-filename with filenamify

---

.github/workflows/docs.yml

This should prevent the "failed to run CI on gh-pages" email notifications from CircleCI whenever there's a push to the default branch.

build(docs): customize docs commit user & prevent CircleCI from running for gh-pages

---

package.json
src/index.ts
src/utils.ts
test/fixtures/electron-v1.0.0-darwin-x64.zip
test/fixtures/electron-v1.0.0-linux-x64.zip
test/fixtures/electron-v1.0.0-win32-x64.zip
test/fixtures/electron-v1.3.3-darwin-x64 copy.zip
test/fixtures/electron-v1.3.3-darwin-x64.zip
test/fixtures/electron-v1.3.3-linux-x64 copy.zip
test/fixtures/electron-v1.3.3-linux-x64.zip
test/fixtures/electron-v1.3.3-win32-x64 copy.zip
test/fixtures/electron-v1.3.3-win32-x64.zip
test/fixtures/electron-v1.3.5-darwin-x64.zip
test/fixtures/electron-v1.3.5-linux-x64.zip
test/fixtures/electron-v1.3.5-win32-x64.zip
test/index.spec.ts
yarn.lock

Fixes #181.
Reimplementation of #25 for `@electron/get`. Adds the `semver` package to check version ranges. Note that semver@6 was used because this module still specifies Node 8.6 support.
🧪 Tests: I don't think existing tests referenced the `sumchecker` module, so I haven't added any tests. Let me know if I should!

fix: skip checksum for versions without shasums256

---

.circleci/config.yml
.github/workflows/docs.yml
yarn.lock

Docs publishing failed as a result of this.
Also prevent this in the future by running `yarn --frozen-lockfile` instead of `yarn` in CI.

chore: sync yarn.lock 

---

package.json
src/Cache.ts
test/Cache.spec.ts
yarn.lock

Fixes #185 by using a checksum of the stripped URL instead of a filenamify version of it.

fix: avoid long paths in cache & lower the number of folders created

---

src/index.ts
src/types.ts
test/GotDownloader.network.spec.ts
test/checksums.spec.ts

We want to add the checksums directly to the published NPM package.  To do so `@electron/get` needs to be able to take the hardcoded list and pass it to sumchecker.  This makes the security chain of our checksums
yarn.lock integrity --> electron npm package --> hardcoded checksums --> remote `electron` binary is validated

feat: support hardcoded checksums

---

.circleci/config.yml

ci(macos): use xcode 13 since 10.2.0 has been removed from CircleCI

---

.gitignore
src/proxy.ts
src/utils.ts
test/utils.spec.ts

see: https://github.com/gajus/global-agent/tree/f82ad8a151af30f5bf218487d006771c6407bf89#what-is-the-reason-global-agentbootstrap-does-not-use-http_proxy
Some libraries (e.g. [`request`](https://npmjs.org/package/request)) change their behaviour when `HTTP_PROXY` environment variable is present. Using a namespaced environment variable prevents conflicting library behaviour.
You can override this behaviour by configuring `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE` variable, e.g.
```bash
$ export GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=
```
Now script initialized using `global-agent/bootstrap` will use `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables.
----
So `ELECTRON_GET_USE_PROXY` was actually not working until now...
This PR will contribute to the improvement of …

feat(proxy): support http(s)_proxy sans prefix on nodejs@>=10

---

src/proxy.ts
src/utils.ts
test/utils.spec.ts

Close: https://github.com/electron/get/issues/215
Sorry. This is a very stupid bug... 🤦‍♂️🤦‍♂️🤦‍♂️
Because:
```js
process.env.A = undefined
process.env.A === 'undefined' // => true
typeof process.env.A // => 'string'
```
cc: @malept

fix: parse proxy error

---

.circleci/config.yml
package.json
src/GotDownloader.ts
yarn.lock

Bumps the dependency on `got` to version 11.8.5, fixing a dependabot alert. `got` also now includes its own type definitions, so the dependency on `@types/got` could be removed as well.

chore!: upgrade got to 11.8.5

---

src/artifact-utils.ts
src/index.ts
src/types.ts
test/checksums.spec.ts
test/index.spec.ts
yarn.lock

Reopened https://github.com/electron/get/pull/219 here because CircleCi didn't want to run builds from forks
Fixes following problems:
* It is not possible to define CUSTOM_VERSION env variable via .npmrc together with others.
* it was not picking up `customDir` and `nightlyMirror` from the `mirrorConfig` properly

fix: support npmrc for custom-version env variable

---

README.md
package.json
src/proxy.ts
yarn.lock

As of v2.0.0, the minimum nodejs version we support is 12. so `global-tunnel-ng` no longer has any effect.
cc: @malept

fix: remove global-tunnel-ng library

---

.github/workflows/docs.yml
.github/workflows/semantic.yml

* Updates and pins SHAs for actions
* Restricts permissions for actions
* Bump Node.js version on docs workflow to v18 to clear deprecation warning

ci: update GitHub actions workflows

---

.github/workflows/docs.yml

Same changes as https://github.com/electron/electron-packager/pull/1547 plus bumping the version of `actions/setup-node`.

ci: fix publish documentation workflow

---

src/types.ts

Uses `@link` notation to link to the target API: https://tsdoc.org/pages/tags/link/
For TypeDoc, this was deprecated in v0.23.0 and removed in v0.24.0: https://typedoc.org/guides/changelog/

docs: [[ target ]] -> {@link target}

---

.github/workflows/docs.yml

Follow-up to #254, looks like this was still defaulting to `master` when we need it to point to `main`.

ci: update publish documentation default branch

---

README.md

this is funny but we've added TypeDoc documentation for the last 5 years but never linked it from the README.
ref https://github.com/electron/get/pull/93

docs: add API docs to readme

---

src/index.ts
src/types.ts

* Fixes all `npm run lint` errors.
* The `Omit` utility type was added into TypeScript 3.5, so we don't need to define our own helper.

chore: minor eslint and type fixes

---

src/index.ts
src/types.ts
src/utils.ts
test/GotDownloader.network.spec.ts
test/index.spec.ts
test/utils.spec.ts

Closes #209. This is less of a problem these days as `@electron/fiddle-core` actually steals the file out of the cache, so there's not duplicate copies, but that's not optimal behavior, and leaves behind `SHASUMS256.txt` files in the cache unnecessarily. So, provide an option to not add the downloaded file to the cache.
Closes electron/packager#1552

feat: cacheMode option

---

package.json
src/Cache.ts
src/GotDownloader.ts
src/index.ts
src/utils.ts
test/GotDownloader.network.spec.ts
test/utils.spec.ts
yarn.lock

build: update prettier to 3.4.2

---

README.md

Now that https://packages.electronjs.org/get/v4.0.0/index.html is live :)

docs: update API documentation link in README

---

package.json
src/Cache.ts
src/GotDownloader.ts
test/GotDownloader.network.spec.ts

Double installs sometimes fight each other for the cache entry, let's back off a bit and then check if the thing in the cache matches the thing we're putting in and if so just accept it.

fix: avoid permission errors on windows during double-installs
